FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY prisma ./prisma
COPY apps/api ./apps/api
COPY packages/shared ./packages/shared

RUN npm run db:generate

WORKDIR /app/apps/api
RUN npm run build

EXPOSE 3001

CMD ["node", "dist/index.js"]